apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-api-db-secret-provider
  namespace: gsn-carrot
spec:
  provider: aws
  parameters:
    region: "ap-northeast-2"
    objects: |
      - objectName: "gsn-carrot-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "split(host, ':') | [0]"
            objectAlias: "DB_HOST"
          - path: "port"
            objectAlias: "DB_PORT"
          - path: "dbname"
            objectAlias: "DB_NAME"
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
  secretObjects:
    - secretName: user-api-db-secret
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
